# Generated by Django 5.1.15 on 2026-06-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма долга')),
                ('debtor_name', models.CharField(blank=True, max_length=255, verbose_name='Должник (вручную)')),
                ('creditor_name', models.CharField(blank=True, max_length=255, verbose_name='Кредитор (вручную)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок погашения')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('partial', 'Частично погашена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='open', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('creditor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts_as_creditor', to=settings.AUTH_USER_MODEL, verbose_name='Кредитор (пользователь)')),
                ('debtor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts_as_debtor', to=settings.AUTH_USER_MODEL, verbose_name='Должник (пользователь)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задолженность',
                'verbose_name_plural': 'Задолженности',
                'ordering': ['-created_at'],
            },
        ),
    ]
