# Generated by Django 5.1.15 on 2026-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='utilities_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма от задолженности, которая при погашении поступит на коммунальные услуги', max_digits=12, verbose_name='На коммунальные услуги'),
        ),
    ]
