# Generated by Django 5.1.15 on 2026-06-19 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_debtors_forward(apps, schema_editor):
  Debt = apps.get_model('debts', 'Debt')
  DebtDebtor = apps.get_model('debts', 'DebtDebtor')
  for debt in Debt.objects.all():
    if debt.debtor_user_id or debt.debtor_name:
      DebtDebtor.objects.create(
        debt=debt,
        debtor_user_id=debt.debtor_user_id,
        debtor_name=debt.debtor_name or '',
        amount=debt.amount,
      )
    elif debt.amount:
      DebtDebtor.objects.create(
        debt=debt,
        debtor_name='Должник',
        amount=debt.amount,
      )


class Migration(migrations.Migration):

  dependencies = [
    ('debts', '0002_debt_utilities_amount'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='DebtDebtor',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('debtor_name', models.CharField(blank=True, max_length=255, verbose_name='Должник (вручную)')),
        ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма долга')),
        ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='debts.debt', verbose_name='Задолженность')),
        ('debtor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_obligations', to=settings.AUTH_USER_MODEL, verbose_name='Должник (пользователь)')),
      ],
      options={
        'verbose_name': 'Должник',
        'verbose_name_plural': 'Должники',
        'ordering': ['id'],
      },
    ),
    migrations.RunPython(migrate_debtors_forward, migrations.RunPython.noop),
    migrations.AlterField(
      model_name='debt',
      name='amount',
      field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма долга'),
    ),
    migrations.RemoveField(
      model_name='debt',
      name='debtor_name',
    ),
    migrations.RemoveField(
      model_name='debt',
      name='debtor_user',
    ),
  ]
