# Generated by Django 5.1.15 on 2026-06-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Заказал')),
                ('is_received', models.BooleanField(default=False, verbose_name='Получил')),
                ('ozon_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка OZON')),
                ('ozon_product_id', models.CharField(blank=True, max_length=32, verbose_name='ID товара OZON')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['id'],
            },
        ),
    ]
