# Generated by Django 5.1.15 on 2026-06-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='debts.debt', verbose_name='Задолженность'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='repaid_by_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кто погашает (вручную)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='repaid_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_repayments', to=settings.AUTH_USER_MODEL, verbose_name='Кто погашает (должник)'),
        ),
        migrations.AlterField(
            model_name='financecategory',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('debt_repayment', 'Погашение задолженности')], max_length=20, verbose_name='Тип'),
        ),
    ]
