# Generated by Django 5.1.15 on 2026-06-19 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_debt_transaction_repaid_by_name_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('direction', models.CharField(choices=[('to_reserve', 'Пополнение резерва'), ('from_reserve', 'Возврат в баланс')], default='to_reserve', max_length=20, verbose_name='Операция')),
                ('source', models.CharField(blank=True, choices=[('balance', 'С основного баланса'), ('external', 'Извне')], max_length=20, verbose_name='Источник')),
                ('date', models.DateField(verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve_transfers', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Операция резерва',
                'verbose_name_plural': 'Операции резерва',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
