# Generated by Django 5.1.15 on 2026-06-19 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debt_utilities_amount'),
        ('finance', '0003_reservetransfer'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='utilities_portion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='На коммунальные'),
        ),
        migrations.CreateModel(
            name='UtilitiesOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('operation_type', models.CharField(choices=[('deposit', 'Пополнение'), ('expense', 'Расход')], max_length=20, verbose_name='Тип операции')),
                ('source', models.CharField(blank=True, choices=[('external', 'Извне'), ('debt', 'Из погашения задолженности')], max_length=20, verbose_name='Источник')),
                ('date', models.DateField(verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilities_credits', to='debts.debt', verbose_name='Задолженность')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilities_operations', to='projects.project', verbose_name='Проект')),
                ('repayment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilities_credit', to='finance.transaction', verbose_name='Погашение')),
            ],
            options={
                'verbose_name': 'Операция (коммунальные)',
                'verbose_name_plural': 'Операции (коммунальные)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
