# Generated by Django 5.1.15 on 2026-06-19 13:25

import django.db.models.deletion
from django.db import migrations, models


def migrate_repayments_forward(apps, schema_editor):
  Transaction = apps.get_model('finance', 'Transaction')
  DebtDebtor = apps.get_model('debts', 'DebtDebtor')
  for tx in Transaction.objects.filter(transaction_type='debt_repayment').exclude(debt_id=None):
    debtors = DebtDebtor.objects.filter(debt_id=tx.debt_id)
    debtor = None
    if tx.repaid_by_user_id:
      debtor = debtors.filter(debtor_user_id=tx.repaid_by_user_id).first()
    if not debtor and tx.repaid_by_name:
      debtor = debtors.filter(debtor_name=tx.repaid_by_name).first()
    if not debtor:
      debtor = debtors.first()
    if debtor:
      tx.debt_debtor_id = debtor.pk
      tx.save(update_fields=['debt_debtor_id'])


class Migration(migrations.Migration):

  dependencies = [
    ('debts', '0003_multi_debtors'),
    ('finance', '0004_transaction_utilities_portion_utilitiesoperation'),
  ]

  operations = [
    migrations.AddField(
      model_name='transaction',
      name='debt_debtor',
      field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='debts.debtdebtor', verbose_name='Должник'),
    ),
    migrations.RunPython(migrate_repayments_forward, migrations.RunPython.noop),
  ]
