# Generated by Django 5.1.15 on 2026-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_multi_debtors'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='skip_utilities',
            field=models.BooleanField(default=False, help_text='Вся сумма погашения пойдёт на долг, без отчисления на коммунальные', verbose_name='Не удерживать коммунальные'),
        ),
    ]
