# Generated by Django 5.1.15 on 2026-06-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_skip_utilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitiesoperation',
            name='balance_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilities_deposit', to='finance.transaction', verbose_name='Списание с баланса'),
        ),
        migrations.AlterField(
            model_name='utilitiesoperation',
            name='source',
            field=models.CharField(blank=True, choices=[('external', 'Извне'), ('balance', 'С основного баланса'), ('debt', 'Из погашения задолженности')], max_length=20, verbose_name='Источник'),
        ),
    ]
