# Generated by Django 5.1.15 on 2026-06-19 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('all_day', models.BooleanField(default=False, verbose_name='Весь день')),
                ('color', models.CharField(default='#8b5cf6', max_length=7, verbose_name='Цвет')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('participants', models.ManyToManyField(blank=True, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['start'],
            },
        ),
    ]
